# Tableau Numpy vs liste Python

## Liste python 

In [9]:
a=[1,2,3]
[q*2 for q in a]

[2, 4, 6]

## array python

In [10]:
import numpy as np
import math
a = np.array([1,2,3])
a*2

array([2, 4, 6])

## Ajouter des elements d'une liste

In [11]:
a = [1,2,3]
b = [4,5,6]
[q+r for q, r in zip(a,b)]

[5, 7, 9]

## Meme Operation array


In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,])
a+b

array([5, 7, 9])

## Ajouter des elements a une liste

In [13]:
a = [1,2,3]

In [14]:
a.append(5)

In [15]:
a

[1, 2, 3, 5]

## Les vecteurs
initialisation


In [16]:
import numpy as np
a = np.array([1,2,3])
a.dtype == np.float64


False

In [17]:
a.shape == (3,)

True

## taille

In [18]:
import numpy as np
b= np.zeros(3,int)
b.dtype == np.int32

True

In [19]:
import numpy as np
c == np.zeros_like(a)
c.dtype == np.float64

False

In [20]:
c.shape == (3,)

True

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.empty(3)

array([1., 1., 1.])

In [24]:
np.full(3,7)

array([7, 7, 7])

In [25]:
np.array([1,2,3])

array([1, 2, 3])

In [26]:
np.zeros_like(a)

array([0, 0, 0])

## initialisation d'un tableau avec une séquence monotone

In [27]:
np.arange(1,6,2)

array([1, 3, 5])

In [28]:
np.arange(2,6)

array([2, 3, 4, 5])

In [29]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
np.linspace(0,0.5,6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

## Tableau aléatoire

In [31]:
np.random.randint(0,10,3)

array([9, 4, 0])

In [32]:
np.random.rand(3)

array([0.67795751, 0.94681568, 0.24282809])

In [33]:
np.random.randn(3)

array([ 1.74396919,  0.33725866, -0.19115439])

In [34]:
np.random.uniform(1,10,3)

array([9.53330197, 6.3514613 , 5.54160442])

In [35]:
np.random.normal(5,2,3)

array([4.59272599, 5.42268156, 5.444107  ])

## indexation vectorielle

In [36]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

## Liste vs numpy array

In [37]:
a = [1,2,3]
b=a
c=a[:]
d=a.copy()

In [38]:
a+b

[1, 2, 3, 1, 2, 3]

In [39]:
a= np.array([1,2,3])
b=a
c=a[:]
d=a.copy()

In [40]:
a+b

array([2, 4, 6])

## Matrices, les tableaux 2D

In [41]:
a=np.array([[1,2,3],[4,5,6]])

In [42]:
a.dtype == np.float64

False

In [43]:
a.shape == (3,4)
a

array([[1, 2, 3],
       [4, 5, 6]])

## Manipulation matricielle
joindre les tableaux


In [67]:
np.hstack((a,c))

array([[ 0.,  1.,  2.,  0.,  1.,  2.],
       [-1.,  0.,  1., -1.,  0.,  1.]])

In [44]:
np.vstack((a,c))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([1,2,3,4])
c = np.array([1,2,3])

In [80]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [73]:
np.hstack((a,c[:, None]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3]])

In [77]:
a= np.column_stack((a,c))
a

array([[ 1,  2,  3,  4,  1,  1],
       [ 5,  6,  7,  8,  2,  2],
       [ 9, 10, 11, 12,  3,  3]])

## arithmetique matricielle

In [45]:
a+b



array([[2, 4, 6],
       [5, 7, 9]])

In [46]:
a*b


array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [47]:
a-b


array([[0, 0, 0],
       [3, 3, 3]])

In [48]:
a@b


array([14, 32])

In [49]:
a/b

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [50]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## the c way vs the python way

In [51]:
c  = [[(j-i) for j in range(3)] for i in range(2)]
a = np.array(c)

In [52]:
a

array([[ 0,  1,  2],
       [-1,  0,  1]])

In [53]:
a= np.empty((2,3))
for i in range(2):
    for j in range(3):
        a[i,j] = j-i

In [54]:
a

array([[ 0.,  1.,  2.],
       [-1.,  0.,  1.]])

## Statistiques matricielles

In [55]:
a.min()

-1.0

In [56]:
a.min(axis=0)

array([-1.,  0.,  1.])

In [57]:
a.min(axis=1)

array([ 0., -1.])